# Generated by Django 4.1.1 on 2022-09-22 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('otp', models.IntegerField(default=459)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('role', models.CharField(max_length=10)),
                ('first_time_login', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=11)),
                ('address', models.TextField(max_length=500)),
                ('job_profile', models.TextField(max_length=500)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('joiningdate', models.DateField(blank=True, null=True)),
                ('salary', models.IntegerField()),
                ('marital_status', models.CharField(max_length=20)),
                ('id_proof', models.FileField(default='static/default.jpg', upload_to='media/images')),
                ('profile_pic', models.FileField(blank=True, null=True, upload_to='media/files')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Manager', to='CEO.user')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=11)),
                ('address', models.TextField(max_length=500)),
                ('job_profile', models.TextField(max_length=500)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('joiningdate', models.DateField(blank=True, null=True)),
                ('salary', models.IntegerField()),
                ('marital_status', models.CharField(max_length=20)),
                ('id_proof', models.FileField(default='static/default.jpg', upload_to='media/images')),
                ('profile_pic', models.FileField(blank=True, null=True, upload_to='media/files')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Employee', to='CEO.user')),
            ],
        ),
        migrations.CreateModel(
            name='CEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=11)),
                ('address', models.TextField(max_length=500)),
                ('profile_pic', models.FileField(default='static/default.jpg', upload_to='media/images')),
                ('gender', models.CharField(max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CEO', to='CEO.user')),
            ],
        ),
    ]
