# Generated by Django 4.1.1 on 2022-09-22 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CEO', '0002_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='email_id',
        ),
    ]
