# Generated by Django 4.1.1 on 2022-09-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CEO', '0004_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=20, null=True),
        ),
    ]
